Update update_paid_feed.yml

diff --git a/.github/workflows/update_paid_feed.yml b/.github/workflows/update_paid_feed.yml
--- a/.github/workflows/update_paid_feed.yml
+++ b/.github/workflows/update_paid_feed.yml
@@ -31,9 +31,13 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          git config --global user.name "GitHub Action"
-          git config --global user.email "action@github.com"
-          git add paid_chapters_feed.xml
-          git commit -m "Update paid feed XML" || echo "No changes to commit"
-          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
-          git push
+          if [ -f paid_chapters_feed.xml ]; then
+              git config --global user.name "GitHub Action"
+              git config --global user.email "action@github.com"
+              git add paid_chapters_feed.xml
+              git commit -m "Update paid feed XML" || echo "No changes to commit"
+              git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
+              git push
+          else
+              echo "File paid_chapters_feed.xml not found"
+          fi
